# Generated by Django 3.2.5 on 2021-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0004_auto_20211123_0032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="hash",
            field=models.BinaryField(blank=True, max_length=16, null=True),
        ),
    ]
