# Generated by Django 3.2.5 on 2021-11-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0005_alter_vacancy_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="site_type_id",
            new_name="site_type",
        ),
    ]
