# Generated by Django 3.2.5 on 2021-11-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20211124_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
