# Generated by Django 3.2.5 on 2021-11-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_vacancy_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='external_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.sitetype'),
        ),
        migrations.AddField(
            model_name='company',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('external_site_id', 'external_url')},
        ),
    ]
