# Generated by Django 3.2.5 on 2021-11-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20211126_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company_link',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='external_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
