# Generated by Django 3.2.5 on 2021-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_auto_20211128_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='company',
            index_together={('external_site_id', 'last_updated')},
        ),
    ]
