# Generated by Django 3.2.5 on 2021-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_auto_20211128_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='sitetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
